-- Global exercise catalog (owner_user_id NULL), seeded once after schema.sql.
-- Run via `npm run db:seed:local` / `db:seed:remote`.
INSERT INTO exercises (name, category, equipment) VALUES
  ('Barbell Bench Press', 'chest', 'barbell'),
  ('Incline Dumbbell Press', 'chest', 'dumbbell'),
  ('Push-Up', 'chest', 'bodyweight'),
  ('Cable Fly', 'chest', 'cable'),
  ('Barbell Back Squat', 'legs', 'barbell'),
  ('Leg Press', 'legs', 'machine'),
  ('Romanian Deadlift', 'legs', 'barbell'),
  ('Walking Lunge', 'legs', 'dumbbell'),
  ('Leg Extension', 'legs', 'machine'),
  ('Leg Curl', 'legs', 'machine'),
  ('Conventional Deadlift', 'back', 'barbell'),
  ('Barbell Row', 'back', 'barbell'),
  ('Lat Pulldown', 'back', 'cable'),
  ('Pull-Up', 'back', 'bodyweight'),
  ('Seated Cable Row', 'back', 'cable'),
  ('Overhead Press', 'shoulders', 'barbell'),
  ('Dumbbell Lateral Raise', 'shoulders', 'dumbbell'),
  ('Face Pull', 'shoulders', 'cable'),
  ('Barbell Curl', 'arms', 'barbell'),
  ('Dumbbell Bicep Curl', 'arms', 'dumbbell'),
  ('Tricep Pushdown', 'arms', 'cable'),
  ('Skull Crusher', 'arms', 'barbell'),
  ('Plank', 'core', 'bodyweight'),
  ('Hanging Leg Raise', 'core', 'bodyweight'),
  ('Cable Crunch', 'core', 'cable'),
  ('Treadmill Run', 'cardio', 'bodyweight'),
  ('Rowing Machine', 'cardio', 'machine'),
  ('Kettlebell Swing', 'full_body', 'dumbbell');
